#!/usr/bin/env python
# -*- coding: utf-8 -*-
#
# Copyright 2015 Develer S.r.l. (http://www.develer.com/)
#
# Permission is hereby granted, free of charge, to any person obtaining a
# copy of this software and associated documentation files (the "Software"),
# to deal in the Software without restriction, including without limitation
# the rights to use, copy, modify, merge, publish, distribute, sublicense,
# and/or sell copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
# DEALINGS IN THE SOFTWARE.
#
# See also:
# https://pip.pypa.io/en/latest/user_guide.html#create-an-installation-bundle-with-compiled-dependencies
#

from __future__ import print_function

from subprocess import check_call as call
import argparse
import contextlib
import glob
import os
import os.path
import shutil
import sys
import tempfile
import zipfile


def main():
    args = parse_args()

    if args.create:
        bundle_create(args.bundle, args.requirements)
    else:
        bundle_install(args.bundle)


def parse_args():
    parser = argparse.ArgumentParser()
    parser.add_argument("-c", "--create", action="store_true")
    parser.add_argument("-r", "--requirements", default="requirements.txt")
    parser.add_argument("bundle", default="bundle.pip-bundle", nargs="?")

    return parser.parse_args()


def bundle_create(bundle_file, requirements):
    if not os.path.isabs(bundle_file):
        bundle_file = os.path.join(os.getcwd(), bundle_file)

    with create_tempdir() as tempdir:
        call(["pip", "wheel", "-r", requirements, "--wheel-dir=" + tempdir])

        with pushd(tempdir):
            mkzip(bundle_file, glob.glob("*.whl"))


def bundle_install(bundle_file):
    if not os.path.isfile(bundle_file):
        print("{0}: No such file, cannot install bundle.".format(bundle_file))
        sys.exit(1)

    with create_tempdir() as tempdir:
        unzip(bundle_file, tempdir)

        with pushd(tempdir):
            call(["pip", "install", "--force-reinstall", "--ignore-installed", "--upgrade", "--no-index", "--no-deps"] + glob.glob("*.whl"))


def mkzip(archive, files):
    with zipfile.ZipFile(archive, "w") as zf:
        for f in files:
            zf.write(f)


def unzip(archive, where):
    with zipfile.ZipFile(archive, "r") as zf:
        zf.extractall(where)


@contextlib.contextmanager
def create_tempdir():
    path = tempfile.mkdtemp(prefix="pip-bundle-")
    yield path
    shutil.rmtree(path)


@contextlib.contextmanager
def pushd(path):
    oldpath = os.getcwd()
    os.chdir(path)
    yield
    os.chdir(oldpath)


if __name__ == '__main__':
    main()
